### ISSUE TITLE
Indicate 5.14 requirement?

### ISSUE THREAD

**Issue by Grinnz** [jonasbn/perl-critic-policy-regularexpressions-requiredefault#3]
The /a modifier requires Perl 5.14, this should probably be mentioned in docs (though it doesn't necessarily mean the Perl that runs this policy needs to be 5.14).

https://perldoc.pl/perl5140delta#%2Fd%2C-%2Fl%2C-%2Fu%2C-and-%2Fa-modifiers

**Comment by jonasbn** [comment]
Hi @Grinnz 

Thanks for the issue report, I have updated the documentation, but also the requirement for Perl version for this distribution, since my test suite, required Perl 5.14.

It will be included in release 0.02 together with an acknowledgement of your contribution.

Have a nice day

jonasbn
